#!/bin/bash
#SBATCH --job-name=bwkmc
#SBATCH --time=0-12:00:00 # wall clock time limit in days-hours:min:seconds
#SBATCH --partition=128x24
#SBATCH --output=bwkmc.out # output file
#SBATCH --error=bwkmc.err # error file
#SBATCH --ntasks=1 # run 1 job
#SBATCH --cpus-per-task=2 # 2 CPUs per job
#SBATCH --mem=4GB # memory limit of 4GB

cd /hb/groups/kelley_training/Emma/bwfastqc_results

./kmc -k21 input.fastq 21mers .
